# Generated by Django 4.0.4 on 2022-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('significado', models.CharField(max_length=200)),
                ('uso', models.CharField(max_length=200)),
            ],
        ),
    ]
